### ISSUE TITLE
Plain Java Version

### ISSUE THREAD

**Issue by BigPanda97** [jankais3r/jPhotoDNA#2]
Based on the article you linked [on your main page](https://hackerfactor.com/blog/index.php?/archives/931-PhotoDNA-and-Limitations.html), would it be possible for you to recreate the algorithm as a plain Java version?
As far as I know, only the name is trademarked by Microsoft. But a new creation of the internal function should be legally possible as far as I know. And it would be platform-independent and fast too.

**Comment by jankais3r** [comment]
Hi, that is outside of the scope of this repository. If I were to re-implement the algorithm based on the provided description, I would do it in Python as that is my language of choice. At this time I don't see enough benefits over using the already available implementation, but I might revisit that in the future (no promise).

**Comment by BigPanda97** [comment]
> At this time I don't see enough benefits over using the already available implementation

A plain Java version of the algorithm would be cross-platform/platform-independent.

**Comment by jankais3r** [comment]
What platform is missing? Linux? You can run the Windows DLL with Wine. If you need to support non-x86 platforms like Arm, you can always spin up QEMU. I am not saying that there is no use for a native re-implementation of the algorithm, but there are already ways to use the existing compiled binaries basically on any possible setup and architecture.

**Update May 16:** Based on this feedback I added Linux support to [pyPhotoDNA](https://github.com/jankais3r/pyPhotoDNA).
