### ISSUE TITLE
Link to download AD_FTK_6.3.0.iso not accessible - in Windows

### ISSUE THREAD

**Issue by RohiniPriyaAlagesan** [jankais3r/jPhotoDNA#4]
Link to download AD_FTK_6.3.0.iso in the batch file is not working. 

How can I get access to AD_FTK_6.3.0.iso & photodnax64.1.72.dll? Thanks

**Comment by jankais3r** [comment]
Hi, thank you for reporting the issue. I updated the download script - please try and report back.

**Comment by RohiniPriyaAlagesan** [comment]
It works great. Thank you.
